### ISSUE TITLE
creacion de tablero kanban

### ISSUE THREAD

**Issue by Angelica-Alzate** [Angelica-Alzate/SMART-VEHICLE#2]

**Comment by Angelica-Alzate** [comment]
se crea el 18 de oct


![Image](https://user-images.githubusercontent.com/111618004/196512015-59f3f495-a376-423f-864d-e00e60913206.png)

**Comment by IvonneCastilla** [comment]
#1 Reunion, socializacion del proyecto y definicion de tareas:
El equipo # 2   continuo con el nombre "BRIGADE CODE"
Se creó el chat en whatsapp para estar comunicados y se designaron los roles:

LIDER: María Angélica Alzate Zuluaga [angelica-9629@hotmail.com](mailto:angelica-9629@hotmail.com)
DISEÑO DESOFTWARE: Jaime Andrés Castro Dulcey [jaimecastro87@gmail.com](mailto:jaimecastro87@gmail.com)
DISEÑO DE INTERFAZ: Ivonne Castilla Manzi [ivonnecastilla@gmail.com](mailto:ivonnecastilla@gmail.com)
TESTER: Diego Andrés Echeverry Sanín [canterack@gmail.com](mailto:canterack@gmail.com)
ADMINISTRADOR DE LA CONFIGURACION: Cristian David García Perez

REUNIONES: 

El 12, 14 y 17  de octubre del 2022 en el "Daily scrum" 8pm , nos reunimos para socializar el proyecto Smart Vehicle. Se leyó en su totalidad, se resolvieron las dudas y  se asignaron las tareas para comenzar el tablero kanban.

TAREAS ASIGNADAS:
Ivonne Castilla: #1,6,8,9
María Angélica Alzate:
Jaime Andres Castro:
Diego Andres Echeverry :
Cristian David Garcia:

SPRINT #1 :

Se analizaron los temas para el sprint 1

-el documento de analisis y diseño de base de datos
-la estructura inicial de la solucion en frontend y backend(microservicios)
-estructura documentada: diagramas
-proyectosde frontend y backend versionados en git
-todas las actividades planeadas en software en linea en kanban
-designacion de tareasde cada rol en kanban

PANTALLAZOS:
Se tomaron los Pantallazos de las reuniones como soporte de actividades:
Daily scrum del 17 de oct/22

![17 oct 2022](https://user-images.githubusercontent.com/111320696/196533839-2631e18c-66f0-40f2-896f-ad3867b2c9c1.png)

Daily scrum del 14 de octubre/22
![Captura de pantalla (413)](https://user-images.githubusercontent.com/111320696/196533575-4356506c-a18d-4e2d-88ef-de8b4d2c05cf.png)

Daily scrum del 12 de octubre/22

![17 oct 2022](https://user-images.githubusercontent.com/111320696/196533107-1a1fd7aa-c080-4b2d-aa8d-7419433bf67a.png)
12oct E2 .png…]()

Tutoria del 12 de octubre /22
8:30pm Tutor: Edwin Giraldo
Equipo #2 Brigade Code
![asistencia 12oct E2 ](https://user-images.githubusercontent.com/111320696/196533747-70cee201-41de-407c-8514-8cc862d26908.png)


PROYECTO    SMART VEHICLE:

La empresa de tecnología "SMART VEHICLE" es una empresa que quiere posicionarse en
el mercado de alquiler y venta de vehículos inteligentes. Sin embargo, se identifica que los usuarios no llegan a finalizar el alquiler o la compra debido a los
procesos tan manuales que existen en la empresa ya que
todo es a través de documentos físicos.
Queriendo sistematizar el proceso de administración de los vehículos, el gerente de SMART
VEHICLE ha contactado con su equipo para desarrollar el sistema que permita realizar toda
esta gestión. Por tal motivo, la Universidad requiere de su apoyo para satisfacer esta
necesidad de SMART VEHICLE.
Para ello, se han realizado reuniones para formalizar los requisitos, obteniendo la siguiente
información:

Sitio web y Módulo de Seguridad:
El sistema deberá contar con un módulo de seguridad que permita la debida gestión de usuarios, roles y permisos de
las personas involucradas.
un. Se debe diseñar un portal web, con las siguientes secciones:
i) home se describe la empresa y se muestran solo los vehículos activos para que sean
visualizados de forma libre por todo el público mediante un filtro de alquiler o compra, ii) la misión
iii) la visión
iv) un formulario de contacto a través del cual se podrá ingresar un mensaje,
los datos de la
persona y un tipo de mensaje (compra o alquiler). Este mensaje será enviado al correo
definido por el administrador en su perfil.
b. Por seguridad, en el sistema de información se debe realizar un formulario de identificación de usuarios, donde a través de las credenciales de acceso (usuario y
contraseña, el usuario será el email de
la persona) tendrán acceso al sistema. La
contraseña deberá ser almacenada de forma cifrada. Solo los usuarios identificados podrán
acceder a las funcionalidades del sistema. Por lo tanto, se debe manejar el control de
sesión de usuario y evitar las inyecciones por URL. (INICIAR SESIÓN)
c. Como segunda medida de seguridad, en el formulario de identificación se debe agregar
un re-captcha (por ejemplo, el que ofrece Google) para verificar que no se trate de acceder
a través de intentos automatizados.
d. Debido a que existen diferentes grupos de personas que interactuarán con el sistema, es
necesario realizar la administración de roles y/o permisos que cada usuario tendrá.
e. También, se podrán agregar nuevos usuarios "Asesores" y modificar los ya existentes. A
los asesores se les deberá ingresar la información personal (incluido el correo electrónico),
y posteriormente se deberá enviar un correo de notificación a los nuevos asesores.
Módulo del Cliente:
Los clientes serán personas naturales que enviarán sus solicitudes para que sean
estudiadas y consideradas para alquilar o comprar un vehículo inteligente. Estos usuarios
deben interactuar con el sistema de información para administrar sus solicitudes y verificar
el estado de cada una de ellas.
un. Un cliente podrá registrarse en el sistema mediante una opción de "registrarse como
cliente" que debe estar en el formulario de identificación del sistema. Este formulario de
registro deberá solicitar la información personal y tener un recaptcha. Después del registro
exitoso, el sistema deberá enviar un mensaje de confirmación al correo registrado en el
formulario.
b. Cuando el cliente ingrese al sistema podrá acceder a diferentes opciones:
i. Solicitar vehículo: en esta opción se podrá filtrar por tipo de solicitud (alquiler o compra) y tipo de vehiculo (carro, moto, patineta), para lo cual, el cliente deberá seleccionar el vehículo que le interesa y
el
sistema le asignará un ID único a dicha solicitud. Cuando un
cliente envía una solicitud, se le debe notificar al asesor encargado del vehículo(el que lo cree en el sistema) con información del cliente que lo
solicitó y los datos del vehículo. Un
vehículo podrá ser solicitado por varios clientes a la vez, y será el asesor quien estudie cada
caso por separado.
ii. Revisar Solicitudes: se debe mostrar un listado de los vehículos que el cliente ha
solicitado mediante el sistema, en el cual se muestra la dirección, el tipo, el valor, la fecha
de solicitud, su estado (enviado, en estudio, aceptado o rechazado), una foto en miniatura
del vehículo que puede ser ampliada en un modal si se hace clic en ella, además deberá
existir un botón de eliminar para aquellas solicitudes que están en estado "enviado". Cuando
el estado de la solicitud es diferente al enviado, se debe mostrar en el lugar de eliminar, una opción para ver los detalles de la solicitud que se abrirán en una
ventana modal.
iii. La opción de eliminación de una solicitud en el listado deberá abrir una opción de confirmación antes de realizar la eliminación del registro de la base de
datos.
iv. Ver resultados de alquiler: el estudio de una solicitud de alquiler (cuando es aceptada o
rechazada) genera una opción donde el usuario puede visualizar los comentarios que hace
el asesor acerca de su solicitud. Dichos comentarios podrán ser descargados en formato
PDF. Cuando una solicitud es "aceptada con co-deudor", se habilitará una opción para
cargar la información personal del co-deudor incluyendo carta laboral, posterior al almacenamiento de esta información la solicitud del vehículo se cambiará automáticamente
al
estado aceptado.
Módulo del Administrador:
El sistema debe permitir al administrador de la empresa tener comunicación con un grupo
de asesores para gestionar los vehículos y las solicitudes de alquiler y/o compra.
un. El rol "Administrador", permitirá gestionar la información de los diferentes asesores.
Cuando se ingrese un nuevo asesor (predeterminadamente se crea con un estado de "pendiente de respuesta"), a su correo electrónico deberá llegar un mensaje de
notificación
sobre su inscripción en el sistema. Además, en ese mismo mensaje se le deberá enviar sus
credenciales de acceso, y un enlace que debe visitar para confirmar o rechazar la invitación.
Dicho enlace es personalizado para cada asesor, y no será necesario iniciar sesión para
aceptar (cambiará el estado a "Asesor") o rechazar (cambiará el estado a "Cancelado") la
invitación. Una vez se hubiese rechazado o aceptado la invitación, el enlace quedará
inhabilitado y si es visitado nuevamente, deberá mostrarse un mensaje donde se diga que
ya fue utilizado. Se recomienda utilizar un identificador hash para cada enlace y así
identificarlo fácilmente.
b. Cuando un asesor acepta o rechaza una invitación, es necesario notificarle al usuario
que lo inscribió sobre el nuevo estado del asesor. Es decir, cualquier miembro Administrador
podrá agregar un asesor, y a ese miembro es a quien se le notificará la decisión del asesor.
c. Un administrador podrá crear los tipos de vehículos que se ofertan en la empresa, la cual
debe tener un nombre, una descripción y un porcentaje de participación en alquiler y/o
compra. También podrá crear los departamentos y las ciudades donde la empresa oferta los
vehículos.
d. Un administrador podrá acceder al listado de solicitudes de todos los clientes, el listado
mostrará los datos relacionados con las solicitudes incluyendo el asesor asociado.
e. El administrador debe indicar la dirección de correo electrónico predeterminada para que
sean enviados los mensajes del formulario de contacto del menú público descrito
inicialmente.
Módulo del Asesor:
El asesor deberá tener funcionalidades para crear vehículos, contactar al cliente, aceptar y
rechazar solicitudes.
un. El asesor podrá visualizar el listado de vehículos a evaluar o solicitudes, donde podrá ver
el ID, el departamento, la ciudad, la dirección, y un botón de estudiar para asignar el estado
de "En estudio". Cuando el asesor tenga una decisión, podrá visitar el listado, y los que
estén en estado "En estudio" les debe aparecer un botón de asignar decisión, donde se
podrá aceptar o rechazar. En el caso de rechazo, se deben ingresar los comentarios
correspondientes. La decisión acerca de la solicitud deberá ser notificada inmediatamente
por el sistema al correo electrónico del cliente con la decisión y además a través de un
mensaje de texto al número celular registrado por el usuario.
b. El asesor, además, podrá administrar (crear, editar, eliminar, etc.) los vehículos. Cuando
se crea un vehículo, el responsable de este será el asesor creador y será a quien le lleguen
las notificaciones cuando el cliente lo solicite. Para un vehículo es necesario ingresar, el departamento, la ciudad, la dirección, el valor, el tipo de vehículo, el
tipo de oferta (venta o
alquiler), encargado, contacto del encargado, fotografías, y enlace a un vídeo de Youtube
(opcional).
c. El asesor podrá también visualizar informes sobre la cantidad de vehículos bajo su cargo
vendidos y/o alquilados en un rango de fechas dado por él mismo.
Requisitos técnicos:
• Vistas de alto rendimiento considerando el funcionamiento asíncrono mediante promesas.
• Usar un framework de CSS para el desarrollo de la GUI. La cual debe considerar principios
de usabilidad, tener apariencia agradable y ser responsiva.
• Los formularios de ingreso de información deberán ser validados y mostrar mensajes
cuando los campos de texto no cumplan con los requisitos solicitados.
• Implementar el sistema mediante tecnologías de desarrollo web (Backend y Frontend) y
plugins relacionados.
• Se pueden implementar otros aspectos que supongan profundizar en alguna de las
tecnologías vistas durante el módulo. Dichos aspectos deberán ser autorizados por el
profesor.
• Comentar el código de manera formal.
• Se debe entregar un documento con el manual de usuario del sistema y un documento con
el análisis y la definición de la base de datos.
• El control de versiones debe ser administrado con Git, y el control de actividades debe ser
llevado a cabo con una herramienta en línea que lo permita como Trello. En ambos casos
deben notificar y agregar al profesor.
Entregas
Sprint 1: Documento de análisis y diseño de base de datos. Además, la estructura inicial de
la solución, tanto en frontend como en backend (microservicios). Esta estructura debe estar
debidamente documentada a través de diagramas y descrita claramente. Los proyectos de
frontend y backend deberán ya estar versionados en git. Finalmente, las actividades
estimadas deben estar planeadas en software en línea como trello - Tablero Kanban, y
debidamente asignadas a cada miembro del equipo de trabajo.

Sprint 2: Punto 1 del enunciado del proyecto (Backend).
Sprint 3: Punto 2 del enunciado del proyecto (Backend).
Sprint 4: Punto 3 del enunciado del proyecto y frontend del punto 1.
Sprint 5: Punto 4 del enunciado del proyecto y frontend del punto 2

**Comment by IvonneCastilla** [comment]
#6
DISEÑO INICIAL DEL HOME
INTERFAZ
![Captura de pantalla (423)](https://user-images.githubusercontent.com/111320696/196569356-03aab92c-56b1-4bc8-82bc-7959b6f1aa61.png)
![Captura de pantalla (425)](https://user-images.githubusercontent.com/111320696/196569371-b466754b-3850-4cde-be98-61610dfcefc1.png)
![Captura de pantalla (424)](https://user-images.githubusercontent.com/111320696/196569382-ba83ea71-7361-429a-ad8e-d484df786b5e.png)


![Captura de pantalla (426)](https://user-images.githubusercontent.com/111320696/196569406-068da4fc-bb39-48b4-8bf1-9642ce062dc4.png)



![Captura de pantalla (433)](https://user-images.githubusercontent.com/111320696/196571080-c3666fd0-e9b4-4db9-9697-697ca4b8b096.png)



![Captura de pantalla (428)](https://user-images.githubusercontent.com/111320696/196569425-2be162cb-3f8c-496e-9e59-5f3f44f8fdee.png)




![Captura de pantalla (429)](https://user-images.githubusercontent.com/111320696/196569429-ba33f3c1-9bc3-4d66-be92-71f2a64e61c8.png)




![Captura de pantalla (430)](https://user-images.githubusercontent.com/111320696/196569433-39db557d-1295-4a06-8e82-7db1dd394610.png)





![Captura de pantalla (431)](https://user-images.githubusercontent.com/111320696/196569443-1f462e66-1039-4372-ad6c-0f80803173fc.png)
